name: Docker CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CURRENT_USER: ManojGowda89
  DEPLOYMENT_DATE: "2025-04-16 05:45:30"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Log build information
      run: |
        echo "Build triggered by: ${{ env.CURRENT_USER }}"
        echo "Deployment timestamp (UTC): ${{ env.DEPLOYMENT_DATE }}"
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          manoj20002/deploymentimage:latest
          manoj20002/deploymentimage:${{ github.sha }}
        build-args: |
          BUILD_DATE=${{ env.DEPLOYMENT_DATE }}
          BUILD_USER=${{ env.CURRENT_USER }}
        labels: |
          org.opencontainers.image.created=${{ env.DEPLOYMENT_DATE }}
          org.opencontainers.image.authors=${{ env.CURRENT_USER }}
          org.opencontainers.image.revision=${{ github.sha }}
          
    - name: Create deployment record
      run: |
        mkdir -p deployment_records
        echo "Deployment performed by: ${{ env.CURRENT_USER }}" > deployment_records/deployment_info.txt
        echo "Deployment date: ${{ env.DEPLOYMENT_DATE }}" >> deployment_records/deployment_info.txt
        echo "Commit SHA: ${{ github.sha }}" >> deployment_records/deployment_info.txt
      
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/app
          echo "Deployment started by ${{ env.CURRENT_USER }} at ${{ env.DEPLOYMENT_DATE }}" >> deployment_log.txt
          docker pull manoj20002/deploymentimage:latest
          docker-compose down
          docker-compose up -d --scale app=3
          echo "Deployment completed at $(date -u '+%Y-%m-%d %H:%M:%S')" >> deployment_log.txt