name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build -t deploymentimage .

      - name: Tag the Docker image
        run: docker tag deploymentimage manoj20002/deploymentimage:latest

      - name: Push the Docker image
        run: docker push manoj20002/deploymentimage:latest

      - name: Pull the Docker image (test)
        run: docker pull manoj20002/deploymentimage:latest
